name: Comment on Pull Requests included in Release
on:
  release:
    types: [published]

jobs:
  comment:
    name: Comment on PRs included in release
    runs-on: ubuntu-latest
    steps:
      - uses: nflaig/release-comment-on-pr@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
